version: '2'
x-redash-service: &redash-service
  image: redash/redash:7.0.0.b18042
  depends_on:
    - postgres
    - redis
  env_file: .redash/env

services:
  server:
    <<: *redash-service
    container_name: redash_server
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    container_name: redash_scheduler
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    container_name: redash_scheduled_worker
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    container_name: redash_adhoc_worker
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis:    
    image: redis:5.0-alpine
    container_name: redash_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.5-alpine
    container_name: redash_postgres
    env_file: .redash/env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: redash/nginx:latest
    container_name: redash_nginx
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash

volumes:
  postgres:
          
networks:
  default:
    external:
      name: hadoop_bridge