version: "3.4"

x-datanode_base: &datanode_base
  image: geunho/hadoop-datanode:2.7.2
  networks:
    - bridge

x-nodemanager_base: &nodemanager_base
  image: geunho/hadoop-nodemanager:2.7.2
  networks:
    - bridge

services:
  namenode:
    image: geunho/hadoop-namenode:2.7.2
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
        - bridge

  resourcemanager:
    image: geunho/hadoop-resourcemanager:2.7.2
    container_name: resourcemanager
    hostname: resourcemanager
    networks:
      - bridge
    ports:
      - 8088:8088
      - 8025:8025
      - 8030:8030
      - 8141:8141
      - 8050:8050

  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
    
  nodemanager01:
    <<: *nodemanager_base
    container_name: nodemanager01
    hostname: nodemanager01
    volumes:
      - datanode01:/opt/hadoop/dfs/data

  datanode02:
    <<: *datanode_base
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/opt/hadoop/dfs/data

  nodemanager02:
    <<: *nodemanager_base
    container_name: nodemanager02
    hostname: nodemanager02
    volumes:
      - datanode02:/opt/hadoop/dfs/data
            
  datanode03:
    <<: *datanode_base
    container_name: datanode03
    hostname: datanode03
    volumes:
      - datanode03:/opt/hadoop/dfs/data

  nodemanager03:
    <<: *nodemanager_base
    container_name: nodemanager03
    hostname: nodemanager03
    volumes:
      - datanode03:/opt/hadoop/dfs/data

  historyserver:
    image: geunho/hadoop-historyserver:2.7.2
    container_name: historyserver
    hostname: historyserver
    networks:
      - bridge
    ports:
      - 8188:8188
  
  proxy:
    image: geunho/hadoop-proxy:latest
    container_name: proxy
    hostname: proxy
    networks:
      - bridge
    ports:
      - 50070:50070
      - 50075:50075
      - 9000:9000
      - 8042:8042
    command: [nginx-debug, '-g', 'daemon off;']
        
volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:
  historyserver:
  
networks:
  bridge: