version: "3"

services:
  namenode:
    image: geunho/hadoop-namenode:2.9.2
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode:/opt/hadoop/dfs/name
    networks:
        - bridge  

  datanode01:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
    networks:
        - bridge  
      
  datanode02:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/opt/hadoop/dfs/data
    networks:
        - bridge  
      
  datanode03:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode03
    hostname: datanode03
    volumes:
      - datanode03:/opt/hadoop/dfs/data
    networks:
        - bridge  
  
  proxy:
    image: geunho/hadoop-proxy:latest
    container_name: proxy
    hostname: proxy
    networks:
      - bridge
    ports:
      - "50070:50070"
      - "50075:50075"
      - "9000:9000"
    command: [nginx-debug, '-g', 'daemon off;']  
        
volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:
networks:
  bridge: