version: "3"

services:
  namenode:
    image: geunho/hadoop-namenode:2.9.2
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
        - bridge

  resourcemanager:
    image: geunho/hadoop-resourcemanager:2.9.2
    container_name: resourcemanager
    hostname: resourcemanager
    networks:
      - bridge
    ports:
      - 8088:8088
      - 8025:8025
      - 8030:8030
      - 8141:8141
      - 8050:8050

  datanode01:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
    networks:
        - bridge

  nodemanager01:
    image: geunho/hadoop-nodemanager:2.9.2
    container_name: nodemanager01
    hostname: nodemanager01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
    networks:
      - bridge

  datanode02:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/opt/hadoop/dfs/data
    networks:
        - bridge

  nodemanager02:
    image: geunho/hadoop-nodemanager:2.9.2
    container_name: nodemanager02
    hostname: nodemanager02
    volumes:
      - datanode02:/opt/hadoop/dfs/data
    networks:
      - bridge
            
  datanode03:
    image: geunho/hadoop-datanode:2.9.2
    container_name: datanode03
    hostname: datanode03
    volumes:
      - datanode03:/opt/hadoop/dfs/data
    networks:
        - bridge

  nodemanager03:
    image: geunho/hadoop-nodemanager:2.9.2
    container_name: nodemanager03
    hostname: nodemanager03
    volumes:
      - datanode03:/opt/hadoop/dfs/data
    networks:
      - bridge
  
  proxy:
    image: geunho/hadoop-proxy:latest
    container_name: proxy
    hostname: proxy
    networks:
      - bridge
    ports:
      - "50070:50070"
      - "50075:50075"
      - "9000:9000"
      - "8042:8042"
    command: [nginx-debug, '-g', 'daemon off;']
        
volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:
networks:
  bridge: