version: "3"

services:
  hiveserver2:
    image: geunho/hive-server2:2.3.5
    container_name: hiveserver2
    hostname: hiveserver2
    volumes:
      - hiveserver2:/opt/hive/data

  tez-ui:
    image: geunho/tez-ui:0.9.2
    container_name: tez-ui
    hostname: tez-ui
    ports:
      - "8080:8080"


volumes:
  hiveserver2:
            
networks:
  default:
    external:
      name: hadoop_bridge