version: "3"

services:
  hiveserver2:
    image: geunho/hive-server2:2.3.5
    container_name: hiveserver2
    hostname: hiveserver2
    depends_on:
      - tez
    volumes:
      - hiveserver2:/opt/hive/data
      - tez_lib:/opt/tez
    ports:
      - 10000:10000

  tez:
    image: geunho/hive-tez:0.9.2
    container_name: tez
    hostname: tez
    volumes:
      - tez_lib:/opt/tez
    ports:
      - 8080:8080

volumes:
  hiveserver2:
  tez_lib:
            
networks:
  default:
    external:
      name: hadoop_bridge